[package]
name = "hello"
version = "0.1.0"
authors = ["xp"]
edition = "2018"

[[bin]]
name = "build-pb"
path = "src/build-pb.rs"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
protoc-rust = { version = "2.8.2" }
protobuf = { version = "=2.8.2" }
grpc = "0.6.2"
